import pandas as pd
import asyncio
import logging
import sys
import io
import traceback
# --- ADK IMPORTS ---
from google.genai import types 
from google.adk.agents import Agent
from google.adk.runners import InMemoryRunner
# Local imports (absolute paths)
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
from utils.shared_environment import shared_env, SHARED_GLOBALS
from config.agent_config import config
# Logging
logging.basicConfig(level=logging.INFO)
# --- UNIVERSAL TOOL (Code Interpreter) ---
def run_python_code(code: str) -> str:
    """
    Executes Python code generated by LLM in a shared environment.
    Use this to load data, clean data, and save files.
    """
    print(f"\n[🤖 Agent Generated Code]:\n{code}\n")
    
    # Capture standard output (print statements)
    old_stdout = sys.stdout
    redirected_output = sys.stdout = io.StringIO()
    
    try:
        # Execute the code within the shared dictionary
        exec(code, SHARED_GLOBALS)
        sys.stdout = old_stdout
        return f"Execution Success. Output:\n{redirected_output.getvalue()}"
    except Exception as e:
        sys.stdout = old_stdout
        return f"Execution Error:\n{traceback.format_exc()}"
def create_logistic_code_executor() -> Agent:
    """Create Logistic Regression Code Executor Agent"""
    return Agent(
        name="Logistic_CodeExecutor_Agent",
        model=config.MODEL_NAME,
        tools=[run_python_code],
        description="Executes specific code lines for logistic regression EDA",
        instruction="""
        <system-reminder>
        LOGISTIC PREPROCESSOR STARTING - Applying data transformations
        </system-reminder>
        You are an Adaptive Data Preprocessor. Your task is to:
        1. Access data from SHARED_GLOBALS["train_data"] and SHARED_GLOBALS["test_data"]
        2. APPLY PREPROCESSING:
        - Handle missing values, encoding, scaling
        - Apply transformations identified in analysis
        3. CRITICAL: Update readiness score to 100%:
        - SHARED_GLOBALS["readiness_score"] = 1.0
        4. CRITICAL: Save ALL datasets to data/processed/ ONLY:
        - import os
        - os.makedirs('data/processed', exist_ok=True)
        - SHARED_GLOBALS["train_data"].to_csv('data/processed/logistic_ready_train.csv', index=False)
        - SHARED_GLOBALS["test_data"].to_csv('data/processed/logistic_ready_test.csv', index=False)
        5. Update SHARED_GLOBALS with final processed data
        <system-reminder>
        LOGISTIC PREPROCESSOR COMPLETED - All datasets saved to data/processed/
        </system-reminder>
        Use the run_python_code tool to execute the preprocessing code.
        """
    )