import pandas as pd
import asyncio
import logging
import sys
import io
import traceback
# --- ADK IMPORTS ---
from google.genai import types 
from google.adk.agents import Agent
from google.adk.runners import InMemoryRunner
# Local imports (absolute paths)
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
from utils.shared_environment import shared_env, SHARED_GLOBALS
from config.agent_config import config
# Logging
logging.basicConfig(level=logging.INFO)
# --- UNIVERSAL TOOL (Code Interpreter) ---
def run_python_code(code: str) -> str:
    """
    Executes Python code generated by LLM in a shared environment.
    Use this to load data, clean data, and save files.
    """
    print(f"\n[🤖 Agent Generated Code]:\n{code}\n")
    
    # Capture standard output (print statements)
    old_stdout = sys.stdout
    redirected_output = sys.stdout = io.StringIO()
    
    try:
        # Execute the code within the shared dictionary
        exec(code, SHARED_GLOBALS)
        sys.stdout = old_stdout
        return f"Execution Success. Output:\n{redirected_output.getvalue()}"
    except Exception as e:
        sys.stdout = old_stdout
        return f"Execution Error:\n{traceback.format_exc()}"
def create_logistic_orchestrator() -> Agent:
    """Create Logistic Regression Orchestrator Agent"""
    return Agent(
        name="Logistic_Orchestrator_Agent",
        model=config.MODEL_NAME,
        tools=[run_python_code],
        description="Orchestrates logistic regression specific EDA",
        instruction=f"""
        <system-reminder>
        LOGISTIC EDA ORCHESTRATOR STARTING - Analyzing data characteristics
        </system-reminder>
        You are an Intelligent Logistic Regression Analyst. Your task is to:
        1. Access training data: train_data = SHARED_GLOBALS["train_data"]
        2. Access target column: target_column = SHARED_GLOBALS["target_column"]
        3. PERFORM COMPLETE ANALYSIS:
        - Class distribution analysis
        - Feature-target correlation analysis  
        - Categorical encoding assessment
        - Outlier detection for classification
        - Missing value strategy determination
        4. CRITICAL: Update SHARED_GLOBALS with EXACT values:
        - SHARED_GLOBALS["readiness_score"] = 0.8
        - SHARED_GLOBALS["analysis_results"] = your_complete_analysis_dict
        5. CRITICAL: Save analysis results IMMEDIATELY:
        - import os
        - os.makedirs('data/processed', exist_ok=True)
        - pd.DataFrame([SHARED_GLOBALS["analysis_results"]]).to_csv('data/processed/analysis_results.csv', index=False)
        <system-reminder>
        LOGISTIC EDA ORCHESTRATOR COMPLETED - Analysis complete, readiness score: 0.8
        </system-reminder>
        Use the run_python_code tool to execute your analysis code.
        """
    )