import pandas as pd
import asyncio
import logging
import sys
import io
import traceback
# --- ADK IMPORTS ---
from google.genai import types 
from google.adk.agents import Agent
from google.adk.runners import InMemoryRunner
# Local imports (absolute paths)
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from utils.shared_environment import shared_env, SHARED_GLOBALS
from utils.data_flow_manager import data_manager
from config.agent_config import config
# Logging
logging.basicConfig(level=logging.INFO)
# --- UNIVERSAL TOOL (Code Interpreter) ---
def run_python_code(code: str) -> str:
    """
    Executes Python code generated by LLM in a shared environment.
    Use this to load data, clean data, and save files.
    """
    print(f"\n[🤖 Agent Generated Code]:\n{code}\n")
    
    # Capture standard output (print statements)
    old_stdout = sys.stdout
    redirected_output = sys.stdout = io.StringIO()
    
    try:
        # Execute the code within the shared dictionary
        exec(code, SHARED_GLOBALS)
        sys.stdout = old_stdout
        return f"Execution Success. Output:\n{redirected_output.getvalue()}"
    except Exception as e:
        sys.stdout = old_stdout
        return f"Execution Error:\n{traceback.format_exc()}"
def create_basic_eda_agent() -> Agent:
    """Create Basic EDA Agent"""
    return Agent(
        name="BasicEDA_Agent",
        model=config.MODEL_NAME,
        tools=[run_python_code],
        description="Performs basic EDA and train/test split",
        instruction=f"""
        <system-reminder>
        BASIC EDA AGENT STARTING - Loading and preprocessing data
        </system-reminder>
        You are an Intelligent Data Preprocessing Specialist. Your task is to:
        1. Load raw dataset from 'data/raw_dataset.csv' into a pandas DataFrame named 'df'
        2. Perform initial data inspection (info, describe, null counts, shape)
        3. Identify target column and store as SHARED_GLOBALS["target_column"]
        4. Perform train/test split (80/20) with stratification
        5. Store as SHARED_GLOBALS["train_data"] and SHARED_GLOBALS["test_data"]
        6. CRITICAL: Save ONLY to data/processed/ directory:
        - import os
        - os.makedirs('data/processed', exist_ok=True)
        - SHARED_GLOBALS["train_data"].to_csv('data/processed/logistic_ready_train.csv', index=False)
        - SHARED_GLOBALS["test_data"].to_csv('data/processed/logistic_ready_test.csv', index=False)
        <system-reminder>
        BASIC EDA AGENT COMPLETED - Data split and saved to data/processed/
        </system-reminder>
        Use 'run_python_code' tool to execute your code.
        """
    )
def create_user_choice_agent() -> Agent:
    """Create User Choice Agent"""
    return Agent(
        name="UserChoice_Agent",
        model=config.MODEL_NAME,
        tools=[run_python_code],
        description="Handles user interaction for regression type selection",
        instruction=f"""
        You are a User Interface Agent. Your task is to:
        1. Present the Basic EDA results to the user
        2. Ask which type of regression analysis they want
        3. Currently only "logistic" is supported
        4. Set the chosen regression type in shared environment
        5. Route to appropriate specialized agent
        
        For now, automatically choose "logistic" and proceed.
        Use 'run_python_code' tool to update the shared environment.
        """
    )